import "@fontsource/poppins";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/400-italic.css";
import SideCheck from "../../Components/Layout/SideCheck";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata = {
  title: "Bench Education",
  description: "Generated by Walton Digitech",
};

export default async function DashboardLayout({ children }) {
  const session = await getServerSession(authOptions);
console.log("session")
  return (
    <section>
      <head>
        <link rel="icon" href="/images/sidenav/logo1-2.png" />
      </head>
      <SideCheck session={session}>
        {children}
      </SideCheck>
    </section>
  );
}
